### ISSUE TITLE
jenkins/ssh-agent:alpine looking for Java in wrong place

### ISSUE THREAD

**Issue by AdamZWinter** [jenkinsci/docker-ssh-agent#127] opened 2022-05-22 19:14 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

I'm following the directions here:  https://www.jenkins.io/doc/book/using/using-agents/

The agent is your alpine image.

The controller is running on the HV, which is Centos 7

### Reproduction steps

Exactly as described here:  https://www.jenkins.io/doc/book/using/using-agents/

sudo docker run -d --rm --name=agent1 -p 4444:22 \
-e "JENKINS_AGENT_SSH_PUBKEY=ssh-rsa [key stuff]" \
jenkins/ssh-agent:alpine

### Expected Results

8.  You should now see This node is being launched.. If that’s not the case, you can now press the Relaunch agent button and wait a few seconds. You can now click on the Log button on the left, then you should receive
the message: Agent successfully connected and online on the last log line.

### Actual Results

SSHLauncher{host='172.17.0.2', port=22, credentialsId='jenkins', jvmOptions='', javaPath='', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=60, maxNumRetries=10, retryWaitTime=15, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.ManuallyTrustedKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[05/22/22 11:57:52] [SSH] Opening SSH connection to 172.17.0.2:22.
[05/22/22 11:57:52] [SSH] SSH host key matches key seen previously for this host. Connection will be allowed.
[05/22/22 11:57:52] [SSH] Authentication successful.
[05/22/22 11:57:52] [SSH] The remote user's environment is:
BASH=/bin/bash
BASHOPTS=checkwinsize:cmdhist:complete_fullquote:extquote:force_fignore:globasciiranges:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="5" [1]="0" [2]="17" [3]="1" [4]="release" [5]="x86_64-alpine-linux-musl")
BASH_VERSION='5.0.17(1)-release'
DIRSTACK=()
EUID=1000
GROUPS=()
HOME=/home/jenkins
HOSTNAME=081269b60664
HOSTTYPE=x86_64
IFS=$' \t\n'
LOGNAME=jenkins
MACHTYPE=x86_64-alpine-linux-musl
MAIL=/var/mail/jenkins
OPTERR=1
OPTIND=1
OSTYPE=linux-musl
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PPID=39
PS4='+ '
PWD=/home/jenkins
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
SSH_CLIENT='172.17.0.1 47632 22'
SSH_CONNECTION='172.17.0.1 47632 172.17.0.2 22'
TERM=dumb
UID=1000
USER=jenkins
_=bash
Checking Java version in the PATH
bash: java: command not found
Java is not in the PATH nor configured with the javaPath setting, Jenkins will try to guess where is Java, this guess will be removed in the future. :Launch agents via SSH
[05/22/22 11:57:52] [SSH] Checking java version of /home/jenkins/jdk/bin/java
Couldn't figure out the Java version of /home/jenkins/jdk/bin/java
bash: /home/jenkins/jdk/bin/java: No such file or directory

[05/22/22 11:57:52] [SSH] Checking java version of java
Couldn't figure out the Java version of java
bash: java: command not found

[05/22/22 11:57:52] [SSH] Checking java version of /usr/bin/java
Couldn't figure out the Java version of /usr/bin/java
bash: /usr/bin/java: No such file or directory

[05/22/22 11:57:52] [SSH] Checking java version of /usr/java/default/bin/java
Couldn't figure out the Java version of /usr/java/default/bin/java
bash: /usr/java/default/bin/java: No such file or directory

[05/22/22 11:57:52] [SSH] Checking java version of /usr/java/latest/bin/java
Couldn't figure out the Java version of /usr/java/latest/bin/java
bash: /usr/java/latest/bin/java: No such file or directory

[05/22/22 11:57:52] [SSH] Checking java version of /usr/local/bin/java
Couldn't figure out the Java version of /usr/local/bin/java
bash: /usr/local/bin/java: No such file or directory

[05/22/22 11:57:52] [SSH] Checking java version of /usr/local/java/bin/java
Couldn't figure out the Java version of /usr/local/java/bin/java
bash: /usr/local/java/bin/java: No such file or directory

java.io.IOException: Java not found on hudson.slaves.SlaveComputer@6caae34b. Install Java 8 or Java 11 on the Agent.
	at hudson.plugins.sshslaves.JavaVersionChecker.resolveJava(JavaVersionChecker.java:83)
	at hudson.plugins.sshslaves.SSHLauncher.lambda$launch$0(SSHLauncher.java:453)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[05/22/22 11:57:52] Launch failed - cleaning up connection
[05/22/22 11:57:52] [SSH] Connection closed.

### Anything else?

bash-5.0# which java
/opt/java/openjdk/bin/java

**Comment by gounthar** [comment] 2022-05-23 13:45
Hi 👋 
I have tried with `jenkins/ssh-agent:jdk11` and `jenkins/ssh-agent:alpine` and only have the problem with `Alpine`.

**Comment by AdamZWinter** [comment] 2022-05-23 19:43
Yes, please note the final part of my comment above, which says:

bash-5.0# which java
/opt/java/openjdk/bin/java

That is, this is the path to java, but the agent launcher isn't looking for it there.

**Comment by gounthar** [comment] 2022-05-25 08:18
The problem may be linked to `ssh` (thanks to @dduportal for pointing that out).
When you try the `docker` image by itself without using `ssh`, the `java` command is found.

**Comment by dduportal** [comment] 2022-05-25 09:58
The problem lies beneath how OpenSSH handles the environment variables.

The Docker image has the environment variable passed to the default user (e.g. `root`); but SSH sessions are different.

It seems that the entrypoint script has an instruction that takes care of this: https://github.com/jenkinsci/docker-ssh-agent/blob/06da0cb7112ac3441a0b392acc5371d4d14b03df/setup-sshd#L53-L54

If I start an agent with this image, and if I check the content of `etc/environment` once SSHD is started, I see that there is a `JAVA_HOME` variable passed. it's ok for Maven, but not for Java itself.


Based on the "fallback" list of the agent, the java prefix used by the eclipse temurin versions is not part of the "usual searched path for the `java` binary (ping @MarkEWaite if you happen to point us in which plugin is this, we could propose a contribution).

However the image should have `java` in its `PATH. Gotta check

**Comment by dduportal** [comment] 2022-05-25 10:01
Gotcha! 

- On debian images, the path is written in `etc/environment` during the build: https://github.com/jenkinsci/docker-ssh-agent/blob/master/8/bullseye/Dockerfile#L60 
- But on alpine images, it is written in `/etc/profile` https://github.com/jenkinsci/docker-ssh-agent/blob/master/8/alpine/Dockerfile#L57 (which is NOT evaluated by the SSH session with the current settings)

**Comment by dduportal** [comment] 2022-05-25 10:09
@gounthar @AdamZWinter as soon as #122 is merged, are you willing to propose a fix PR on the 3 alpine images (not only JDK8)? The idea would be to write in `/etc/environment` on Alpine?

**Comment by gounthar** [comment] 2022-05-25 10:48
Sure, I can try that.
Thanks a bunch for the detailed explanation @dduportal 🙏 .

**Comment by gounthar** [comment] 2022-05-30 16:32
I have mostly finished my #128 PR thanks to the guidance of @dduportal .
If it gets merged soon, @AdamZWinter you should see the results in a few days if you issue a `docker pull`.

**Comment by gounthar** [comment] 2022-05-30 17:30
Did I introduce a regression of some sort? 😟

**Comment by dduportal** [comment] 2022-05-30 17:33
Sorry, I reopened because the image wasn't pushed yet, but I can confirm that it is builts, pushed and fixed now:

**Comment by dduportal** [comment] 2022-05-30 17:36
```console
$ docker run --pull -d --rm --name=agent1 -p 22:22 -e "JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYlEZmGs43NHtJysZpSJX/THB2JBcCP0o+8ijJVAADhzuRYE5Jdd+dwdCWyGzGc8r2pxdw+1l3NHHkhRqTWIgH9h77VLnavrqDf6dTuC05q4RTBw5E6AknKB3L0a4IzpXtvT+MbdkkJaNEFWpK63oGSxbO2kaTUXzYiJg/BnpMo8gKyeF1t1RBZ249xgWqmb4SDkM7hOLC7HF8rJjHXNFvhBAm99aWwr0MhFwmEp6fRAiI5AC52owIewXN9dkXs8oMXjQ4J6g7dO5Vwdu2M19Uk0DbaqEJmngoSYtOikpkFSlnJO3iOqYUXh6uEZLd1OjZbxbcvnmxMlI6UfKkVaKGWzLb6G8yz+Ahz9oxKmq11QsUoMedHZlwHNgPpJ+TS3p5TlDZYGsuVRm7EnMN0+KecXzoZk6i/kJO+uQ0oMxdtZCYVlwdTiOW/85WqB7lSVokIWAkRmV89kHEbgSJLgrH9aXr4xw2jhzN+F9HT2Z5mOoVU3Exkursu/bXhdocIhdtXQVBDIA0hcvouUGar6Db7VK6NQeJoAWUVVELhBZP+rGhbg5WjGZANPPi01VMIDhks5KXZt0AtaQxpZCaynbasm0g7fHvy+BP3bTQcpa95hBWYL0tjon5BPLTkzK4q282pQluba0bralLDgF0SoNw4F83w/hu7YwHMoSC9Njzcw==" jenkins/ssh-agent:alpine-jdk8

$ ssh jenkins@localhost -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null java -version
Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.332-b09, mixed mode)
```


```console
$docker run --pull -d --rm --name=agent1 -p 22:22 -e "JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYlEZmGs43NHtJysZpSJX/THB2JBcCP0o+8ijJVAADhzuRYE5Jdd+dwdCWyGzGc8r2pxdw+1l3NHHkhRqTWIgH9h77VLnavrqDf6dTuC05q4RTBw5E6AknKB3L0a4IzpXtvT+MbdkkJaNEFWpK63oGSxbO2kaTUXzYiJg/BnpMo8gKyeF1t1RBZ249xgWqmb4SDkM7hOLC7HF8rJjHXNFvhBAm99aWwr0MhFwmEp6fRAiI5AC52owIewXN9dkXs8oMXjQ4J6g7dO5Vwdu2M19Uk0DbaqEJmngoSYtOikpkFSlnJO3iOqYUXh6uEZLd1OjZbxbcvnmxMlI6UfKkVaKGWzLb6G8yz+Ahz9oxKmq11QsUoMedHZlwHNgPpJ+TS3p5TlDZYGsuVRm7EnMN0+KecXzoZk6i/kJO+uQ0oMxdtZCYVlwdTiOW/85WqB7lSVokIWAkRmV89kHEbgSJLgrH9aXr4xw2jhzN+F9HT2Z5mOoVU3Exkursu/bXhdocIhdtXQVBDIA0hcvouUGar6Db7VK6NQeJoAWUVVELhBZP+rGhbg5WjGZANPPi01VMIDhks5KXZt0AtaQxpZCaynbasm0g7fHvy+BP3bTQcpa95hBWYL0tjon5BPLTkzK4q282pQluba0bralLDgF0SoNw4F83w/hu7YwHMoSC9Njzcw==" jenkins/ssh-agent:alpine-jdk11

$ ssh jenkins@localhost -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null java -version
Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)
```

```console
$ docker run --pull -d --rm --name=agent1 -p 22:22 -e "JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYlEZmGs43NHtJysZpSJX/THB2JBcCP0o+8ijJVAADhzuRYE5Jdd+dwdCWyGzGc8r2pxdw+1l3NHHkhRqTWIgH9h77VLnavrqDf6dTuC05q4RTBw5E6AknKB3L0a4IzpXtvT+MbdkkJaNEFWpK63oGSxbO2kaTUXzYiJg/BnpMo8gKyeF1t1RBZ249xgWqmb4SDkM7hOLC7HF8rJjHXNFvhBAm99aWwr0MhFwmEp6fRAiI5AC52owIewXN9dkXs8oMXjQ4J6g7dO5Vwdu2M19Uk0DbaqEJmngoSYtOikpkFSlnJO3iOqYUXh6uEZLd1OjZbxbcvnmxMlI6UfKkVaKGWzLb6G8yz+Ahz9oxKmq11QsUoMedHZlwHNgPpJ+TS3p5TlDZYGsuVRm7EnMN0+KecXzoZk6i/kJO+uQ0oMxdtZCYVlwdTiOW/85WqB7lSVokIWAkRmV89kHEbgSJLgrH9aXr4xw2jhzN+F9HT2Z5mOoVU3Exkursu/bXhdocIhdtXQVBDIA0hcvouUGar6Db7VK6NQeJoAWUVVELhBZP+rGhbg5WjGZANPPi01VMIDhks5KXZt0AtaQxpZCaynbasm0g7fHvy+BP3bTQcpa95hBWYL0tjon5BPLTkzK4q282pQluba0bralLDgF0SoNw4F83w/hu7YwHMoSC9Njzcw==" jenkins/ssh-agent:alpine-jdk17

$ ssh jenkins@localhost -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null java -version
Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
```

**Comment by dduportal** [comment] 2022-05-30 17:37
Many thanks @gounthar

**Closed by dduportal** 2022-05-30 17:36 UTC
Labels: bug
